version: "3.8"
services:
  barravento:
    build: ./barravento
    container_name: barravento
    ports:
      - "7077:7077"
      - "8080:8080"
      - "9200:9200"
      - "9870:9870"
      - "9000:9000"
    volumes:
      - ./requirements_python.txt:/root/requirements_python.txt:ro
    networks:
      - cluster_net
  jardimdealah:
    build: ./jardimdealah
    container_name: jardimdealah
    volumes:
      - ./requirements_python.txt:/root/requirements_python.txt:ro
    networks:
      - cluster_net
  stellamaris:
    build: ./stellamaris
    container_name: stellamaris
    volumes:
      - ./requirements_python.txt:/root/requirements_python.txt:ro
    networks:
      - cluster_net
  lagamar:
    build: ./lagamar
    container_name: lagamar
    ports:
      - "8888:8888"
      - "2222:22"
    volumes:
      - ./requirements_python.txt:/root/requirements_python.txt:ro
    networks:
      - cluster_net

networks:
  cluster_net:
    driver: bridge
