version: '3.9'

services:
  spark-master:
    image: bitnami/spark:3.0.1
    environment:
      - SPARK_MODE=master
      - SPARK_DRIVER_MEMORY=3g
    ports:
      - "8080:8080"
    networks:
      - sparknet

  spark-worker-1:
    image: bitnami/spark:3.0.1
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_CORES=4
      - SPARK_WORKER_MEMORY=8g
      - SPARK_MASTER_URL=spark://spark-master:7077
    ports:
      - "8081:8081"
    networks:
      - sparknet

  spark-worker-2:
    image: bitnami/spark:3.0.1
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_CORES=4
      - SPARK_WORKER_MEMORY=8g
      - SPARK_MASTER_URL=spark://spark-master:7077
    ports:
      - "8082:8081"
    networks:
      - sparknet

  hdfs-namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://hdfs-namenode:9000
    ports:
      - "9870:9870"
    volumes:
      - namenode:/hadoop/dfs/name
    networks:
      - sparknet

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - sparknet

  spark-submit:
    build:
      context: ./ssh
    ports:
      - "2222:22"
    networks:
      - sparknet
    depends_on:
      - spark-master
      - spark-worker-1
      - hdfs-namenode
      - elasticsearch

volumes:
  namenode:

networks:
  sparknet:
